network:
  version: 2
  ethernets:
    eth0:
      match:
        macaddress: "00:0d:3a:a2:4a:cc"
        driver: "hv_netvsc"
      dhcp4: true
      dhcp4-overrides:
        route-metric: 100
      dhcp6: false
      set-name: "eth0"
